(function(i){if(typeof _MLTrackerz==="undefined"){_MLTrackerz=null;var g,f=_MLTrackerz=function(a){return new f.prototype.init(a)};f.extend=function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a};f.extend(f,{idle:[1,1],joinParameters:function(a,b){var c=[],d;if(b===",")for(d in a)a.hasOwnProperty(d)&&a[d]!==""&&a[d]!=i&&Array.prototype.push.call(c,a[d]);else if(b==="&")for(d in a)a.hasOwnProperty(d)&&a[d]!==""&&a[d]!=i&&Array.prototype.push.call(c,d+"="+a[d]);return c.join(b)},getCurrentUrl:function(){var a=
"";try{a=top.location.href}catch(b){try{a=document.referrer}catch(c){}}return encodeURIComponent(a)},getPreviousUrl:function(){var a="";try{a=top.document.referrer}catch(b){}return encodeURIComponent(a)},getQueryString:function(a){var b,c={},d,k,e;if(!f.queryString){try{b=top.location.search}catch(g){b=location.search}if(b){b=b.substr(1);b=b.split("&");for(d=0,k=b.length;d<k;d++)e=b[d].split("="),e.length===2&&(c[e[0]]=e[1])}f.queryString=c}return f.queryString[a]},getCookieEnabled:function(){return navigator.cookieEnabled?
1:0},getFlashVersion:function(){var a="0,0,0,0";try{navigator.plugins&&navigator.plugins["Shockwave Flash"]?a=navigator.plugins["Shockwave Flash"].description:window.ActiveXObject&&new ActiveXObject("ShockwaveFlash.ShockwaveFlash")&&(a=(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version"))}catch(b){}a=a.match(/\d+/g);return a[0]},send:function(a){var b=document.createElement("img"),c=document.getElementsByTagName("script")[0];b.style.display="none";c.parentNode.insertBefore(b,
c);b.src=a},mappimg:function(){var a=document.createElement("iframe"),b=document.body?document.body.firstChild:document.getElementsByTagName("script")[0];a.style.display="none";a.src="http://static.mlt01.com/mltmap.htm";b.parentNode.insertBefore(a,b)},load:function(a,b,c,d,f){var e,g=/loaded|complete/i,h="script_$"+Math.ceil(Math.random()*1E10);b?(e=document.createElement("script"),e.type="text/javascript",e.async=!0,e.charset="utf-8",e.id=h,e.src=a,a=document.getElementsByTagName("script")[0],a.parentNode.insertBefore(e,
a)):(window.ActiveXObject&&(g=/complete/i),document.write('<script type="text/javascript" charset="utf-8" src="'+a+'" id="'+h+'"><\/script>'));if(e=document.getElementById(h))e.onload=e.onreadystatechange=function(){var j;if(!e.readyState||e.readyState.match(g))if(typeof c==="function"&&c(),f=c=null,e&&e.parentNode)j=e.onload=e.onreadystatechange=null,e=j},e.onerror=function(){typeof f==="function"&&f();f=c=null};d&&setTimeout(function(){if(e)typeof f==="function"&&f(),d=f=null,e.src="javascript:void(0)"},
d)},getTopDomain:function(a){if(!arguments.callee.domain){for(var b=(a||location.hostname).split("."),c=/com|edu|gov|int|mil|net|org|biz|info|pro|name|museum|coop|aero|xxx|idv/,d=b.length-1,f=b.length-1,e=0;d>-1;d--)if(c.test(b[d])){f=d;break}else/\d+/.test(b[d])&&e++;b.length==e&&(f=1);arguments.callee.domain=b.slice(f-1).join(".")}return arguments.callee.domain},cookie:function(a,b,c){if(typeof b!=="undefined"){if(b===null)b="",c=c||{},c.expires=-1;a=a+"="+b;c&&(c.path&&(a+="; path="+c.path),c.expires instanceof
Date&&(a+="; expires="+c.expires.toGMTString()),c.domain&&(a+="; domain="+c.domain),c.secure&&(a+="; secure"));document.cookie=a}else return RegExp(";?"+a+"=([^;]*);?").test(document.cookie)?RegExp.$1:null},fc:function(){}});f.prototype={constructor:"_MLTrackerz",jsv:9,init:function(a){if(a.mid){var b,c;this.mid=a.mid;this.st=a.st;this.ecc=window!=top?1:0;if(a.ecc)this.ecc=a.ecc;b=this.zcookie("mltn");this.zcookie("mlts");c=this.zcookie("mlti");g="."+f.getTopDomain();if(g.lastIndexOf(".")<1||!/\w/.test(g))g=
null;b||this.zcookie("mltn","0>0>0>0>0>0",{domain:g,expires:new Date((new Date).getTime()+15552E6),path:"/"});c||this.zcookie("mlti",(new Date).getTime()+""+Math.floor(Math.random()*1E5),{domain:g,expires:new Date((new Date).getTime()+15552E6),path:"/"});if(a.serverbaseurl)this.serverbaseurl=a.serverbaseurl;for(b=0,c=a.ers.length;b<c;b++)this.track(a.ers[b])}},zcookie:function(a,b,c){var d=this.mid,g=RegExp("@"+d+"~([^@]+)+@"),e=f.cookie(a);if(typeof b!=="undefined")b=e?g.test(e)?e.replace(g,"@"+
d+"~"+b+"@"):e+"@"+d+"~"+b+"@":"@"+d+"~"+b+"@",f.cookie(a,b,c);else return e&&g.test(e)?RegExp.$1:null},track:function(a){var b=this;(function(){if(f.idle[1]){var c=b.getServerUrl()+b.getParameters(a),d=function(){f.idle[1]=1};f.idle[1]=0;b.cer=a;f.load(c,1,d,1E4,d)}else setTimeout(arguments.callee,0)})()},generateCurrentUrl:function(a){var b="";try{b=a.indexOf("/")===0?top.location.protocol+"//"+top.location.host+a:/^https?:\/\//.test(a)?a:top.location.protocol+"//"+top.location.host+top.location.pathname.slice(0,
top.location.pathname.lastIndexOf("/"))+"/"+a}catch(c){b=a.indexOf("/")===0?location.protocol+"//"+location.host+a:/^https?:\/\//.test(a)?a:location.protocol+"//"+location.host+location.pathname.slice(0,location.pathname.lastIndexOf("/"))+"/"+a}return encodeURIComponent(b)},getParameters:function(a){var b,c={rct:"html",g:0,mid:this.mid,st:this.st,u:[f.getCookieEnabled(),f.getFlashVersion()].join(","),sr:[screen.width,screen.height].join(","),dt:""},d=this.zcookie("mltis"),g=this.zcookie("mlts"),e=
this.zcookie("mltn"),j=this.zcookie("mlti"),h=this.zcookie("mltr");if(d)d=d.split(">"),c.aid=d[1],c.bid=d[2],c.cid=d[3];if(g)g=g.split(">"),c.src=g.join(",");if(e&&(e=e.split(">"),e[0]!=0))c.ssn=e.join(",");if(this.ecc)c.curl=encodeURIComponent(document.referrer);a.path&&a.type==="pageview"?(c.purl=this._purl||f.getCurrentUrl(),c.curl=this.generateCurrentUrl(a.path),this._purl=c.curl,a.path=null):c.purl=f.getPreviousUrl();c.iei=0;if(top!=window)c.iei=1;if(h)c.rfr=encodeURIComponent(h);c.jsv=this.jsv;
if(typeof a==="object")for(b in a)a.hasOwnProperty(b)&&a[b]!==""&&a[b]!=i&&(c[b.toLowerCase()]=encodeURIComponent(a[b]));if(f.cookie("__utmz"))c.gml=f.cookie("__utmz");if(j)c.fvid=j;return f.joinParameters(c,"&")},s:function(a,b,c,d,f,e,j,h,i,l){switch(a){case 1:this.zcookie("mltis",[a,b||0,c||0,d||0].join(">"),{domain:g,expires:new Date((new Date).getTime()+2592E6),path:"/"});this.zcookie("mlts",[a,encodeURIComponent(b||0),encodeURIComponent(c||0),encodeURIComponent(d||0),f||0,e||0,encodeURIComponent(j||
""),encodeURIComponent(h||""),encodeURIComponent(i||""),encodeURIComponent(l||"")].join(">"),{domain:g,expires:new Date((new Date).getTime()+15552E6),path:"/"});break;case 2:this.zcookie("mlts",[a,encodeURIComponent(b||""),encodeURIComponent(c||""),encodeURIComponent(d||""),encodeURIComponent(f||""),encodeURIComponent(e||"")].join(">"),{domain:g,expires:new Date((new Date).getTime()+15552E6),path:"/"});break;case 3:this.zcookie("mlts",[a,encodeURIComponent(b||""),encodeURIComponent(c||"")].join(">"),
{domain:g,expires:new Date((new Date).getTime()+15552E6),path:"/"});break;case 4:this.zcookie("mlts",[a,encodeURIComponent(b||"")].join(">"),{domain:g,expires:new Date((new Date).getTime()+15552E6),path:"/"});break;case 5:this.zcookie("mlts",""+a,{domain:g,expires:new Date((new Date).getTime()+15552E6),path:"/"});break;case 6:this.zcookie("mltis",[a,b||0,c||0,d||0].join(">"),{domain:g,expires:new Date((new Date).getTime()+2592E6),path:"/"}),this.zcookie("mlts",[a,b||0,c||0,d||0,encodeURIComponent(f||
""),encodeURIComponent(e||""),encodeURIComponent(j||""),encodeURIComponent(h||""),encodeURIComponent(i||"")].join(">"),{domain:g,expires:new Date((new Date).getTime()+15552E6),path:"/"})}},n:function(a,b,c){var d=this.zcookie("mltn");d&&(d=d.split(">"),d[0]!=a&&(d[1]=0,d[3]=0),this.cer.type==="pageview"&&(d[3]=parseInt(d[3],10)+1,d[4]=b),d[6]||(d[6]=b),d[0]=a,d[1]=parseInt(d[1],10)+1,d[2]=b,d[5]=c||0,this.zcookie("mltn",d.join(">"),{domain:g,expires:new Date((new Date).getTime()+15552E6),path:"/"}),
f.cookie("mltmapping")||f.mappimg(),f.cookie("mltmapping",1,{domain:g,expires:new Date((new Date).getTime()+2592E6),path:"/"}))},r:function(a){a&&this.zcookie("mltr",a,{domain:g,expires:new Date((new Date).getTime()+2592E6),path:"/"})},getServerUrl:function(){return(location.protocol==="https:"?"https://":"http://")+this.getBaseUrl()+(location.protocol==="https:"?"snact.htm?":"nact.htm?")},getBaseUrl:function(){return this.serverbaseurl?this.serverbaseurl:location.protocol==="https:"?"secure.mlt01.com/":
"minisite.mlt01.com/"}};f.prototype.init.prototype=f.prototype}})();typeof MLTrackerz!=="undefined"&&MLTrackerz.constructor!=="_MLTrackerz"&&(MLTrackerz=_MLTrackerz(MLTrackerz));typeof MLTTrackerz!=="undefined"&&MLTTrackerz.constructor!=="_MLTrackerz"&&(MLTTrackerz=MLTrackerz=_MLTrackerz(MLTTrackerz));typeof MltTracker!=="undefined"&&MltTracker.constructor!=="_MLTrackerz"&&(MltTracker=MLTrackerz=_MLTrackerz(MltTracker));
